# ---- LINKS ----
# @link: https://docs.docker.com/network/
# @note: 
# ---------------

version: "3.7"

# my-test:
#   image: hello-world

###############################################################################
#                             NETWORKS                                        #
#/////////////////////////////////////////////////////////////////////////////#

networks:
  inception_network:
    name: inception_network
    driver: bridge

###############################################################################
#                             VOLUMES                                         #
#/////////////////////////////////////////////////////////////////////////////#

volumes: # For using backup all things.
  wp:
    name: wp
    # env_file: .env
    # env_printer:
      # image: "helloooasdf"
    # environment:
      # - asdf=asdf
    driver: local # We indicate that it works in locale, we can also write an ip address.
    driver_opts:
      type: none
      o: bind
      # device: /home/gorkem/data/wp #volume path
      device: /home/${USER}/data/wp #volume path
      # device: ${VOLUMES_WP} #volume path
  db:
    name: db
    # env_file: .env
    # env_printer:
      # image: "helloooasdf"
    # environment:
      # - asdf=asdf
    driver: local # We indicate that it works in locale, we can also write an ip address.
    driver_opts:
      type: none
      o: bind
      # device: /home/gorkem/data/db #volume path
      device: /home/${USER}/data/db #volume path
      # device: ${VOLUMES_DB} #volume path
  prt:
    name: prt
    # env_file: .env
    # env_printer:
      # image: "helloooasdf"
    # environment:
      # - asdf=asdf
    driver: local # We indicate that it works in locale, we can also write an ip address.
    driver_opts:
      type: none
      o: bind
      # device: /home/gorkem/data/prt #volume path
      device: /home/${USER}/data/prt #volume path
      # device: ${VOLUMES_PRT} #volume path

###############################################################################
#                             SERVICES                                        #
#/////////////////////////////////////////////////////////////////////////////#

services: # For containers(services).
  # _____NGINX______ #
  nginx: # For 'Web Server'.
    container_name: nginx # PDF asks us to create it with this name.
    build: ./requirements/nginx/ # Container's 'Dockerfile' path location for run this file.
    env_file: .env
    volumes:
      - wp:/var/www/wordpress
    networks:
      - inception_network
    depends_on:
      - wordpress
    ports:
      - "443:443" # Local port / Exported port.
  # ________________ #
  # ____WORDPRESS___ #
  wordpress:
    container_name: wordpress # PDF asks us to create it with this name.
    build: ./requirements/wordpress/
    env_file: .env
    volumes:
      - wp:/var/www/wordpress
    networks:
      - inception_network
    # depends_on:
      # - mariadb
  # ________________ #
  # ____MARIADB_____ #
  mariadb:
    container_name: mariadb # PDF asks us to create it with this name.
    restart: always # If this container is closed, it restarts.
    build: ./requirements/mariadb/ # Dockerfile path locaiton.
    env_file: .env
    volumes:
      - db:/var/lib/mysql # Mirroring this location to this location.
    networks:
      - inception_network # Using network.
  # ________________ #