# ---- LINKS ----
# @link: https://docs.docker.com/network/
# @note: 
# ---------------

version: "3"

# my-test:
#   image: hello-world

###############################################################################
#                             NETWORKS                                        #
#/////////////////////////////////////////////////////////////////////////////#

networks:
  inception_network:
    # name: inception_network
    driver: bridge

###############################################################################
#                             VOLUMES                                         #
#/////////////////////////////////////////////////////////////////////////////#

volumes: # For using backup all things and reach all files inside container.
  wordpress_data:
    # env_file: .env
    # env_printer:
      # image: "helloooasdf"
    # environment:
      # - asdf=asdf
    driver: local # We indicate that it works in locale, we can also write an ip address.
    driver_opts:
      type: none
      o: bind
      # device: /home/gsever/data/wordpress #volume path
      device: /home/${USER}/data/wordpress #volume path
      # device: ${VOLUMES_WP} #volume path
  mariadb_data:
    driver: local # We indicate that it works in locale, we can also write an ip address.
    driver_opts:
      type: none
      o: bind
      # device: /home/gsever/data/mysql #volume path
      device: /home/${USER}/data/mysql #volume path
      # device: ${VOLUMES_DB} #volume path
  # prt:
  #   name: prt
  #   driver: local # We indicate that it works in locale, we can also write an ip address.
  #   driver_opts:
  #     type: none
  #     o: bind
  #     # device: /home/gsever/data/prt #volume path
  #     device: /home/${USER}/data/prt #volume path
  #     # device: ${VOLUMES_PRT} #volume path

###############################################################################
#                             SERVICES                                        #
#/////////////////////////////////////////////////////////////////////////////#

services: # For containers(services).
  # _____NGINX______ #
  nginx: # For 'Web Server'.
    container_name: nginx # PDF asks us to create it with this name.
    build: ./requirements/nginx/ # Container's 'Dockerfile' path location for run this file.
    env_file: .env
    volumes:
      - wordpress_data:/var/www/html
      # - wordpress_data:/etc/ssl/
    networks:
      - inception_network
    restart: always
    ports:
      - 443:443 # Local port / Exported port.
    depends_on:
      - adminer
      - redis
      - hugo
  # ________________ #
  # ____MARIADB_____ #
  mariadb:
    container_name: mariadb # PDF asks us to create it with this name.
    build: ./requirements/mariadb/ # Dockerfile path locaiton.
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql # Mirroring this location to this location.
    networks:
      - inception_network # Using network.
    restart: always # If this container is closed, it restarts.
    # ports:
      # - 3306:3306
  # ________________ #
  # ____WORDPRESS___ #
  wordpress:
    container_name: wordpress # PDF asks us to create it with this name.
    build: ./requirements/wordpress/
    # build:
    #   context: ./requirements/wordpress
    #   dockerfile: Dockerfile
    env_file: .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network
    restart: always # If this container is closed, it restarts.
    depends_on:
      - mariadb
  # ________________ #


  #### BONUS PART ####
  # ____ADMINER_____ #
  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer/
    networks:
      - inception_network
    restart: always
    expose:
      - "9000"
    # ports:
      # - "8080:8080"
    depends_on:
      - mariadb
  # ________________ #
  # ___REDIS_CACHE__ #
  redis:
    container_name: redis
    build: ./requirements/bonus/redis/
    env_file: .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network
    restart: always
    ports:
      - "6379:6379"
    depends_on:
      - wordpress
  # ________________ #
  # ___FTP-SERVER___ #
  ftp-server:
    container_name: ftp-server
    build: ./requirements/bonus/ftp_server/
    env_file: .env
    environment:
      FTP_USR: ${FTP_USR}
      FTP_PWD: ${FTP_PWD}
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network
    restart: always
    ports:
      - "21:21"
      - "21000-21010:21000-21010" #port aralığı
  # ________________ #
  # _____HUGO_______ #
  hugo:
    container_name: hugo
    build: ./requirements/bonus/hugo
    networks:
      - inception_network
    restart: always
  # ________________ #
  # __STATIC-PAGE___ #
  static_page:
    container_name: static_page
    build: ./requirements/bonus/static_page
    networks:
      - inception_network
    restart: always
  # ________________ #