baseURL = "https://gsever.42.fr/me"
theme = "m10c"
paginate = 8
canonifyURLs = true

[params]
  author = "Görkem SEVER"
  description = "Dedicated hugo service for inception project"


###############################################################################
# COMMENT LINES

# `Hugo` ve `Wordpress`, farklı türde içerik yönetim sistemleri (CMS) veya site
#   oluşturma araçlarıdır. İşte `Hugo` ile `Wordpress` arasındaki temel farklar:

# Tür ve Mimarisi:
# `Hugo`: `Hugo`, bir statik site oluşturma aracıdır. Statik siteler, sunucuların
#   her istekte içeriği dinamik olarak oluşturmak yerine önceden oluşturulmuş
#   dosyaları sunarak daha hızlı ve güvenli bir deneyim sunabilir.
# `Wordpress`: `Wordpress` ise dinamik bir içerik yönetim sistemidir. PHP ve
#   veritabanı kullanarak içeriği her istekte dinamik olarak oluşturur.

# Çalışma Prensibi:
# `Hugo`: `Hugo`, içerik dosyalarını ve şablonları kullanarak statik HTML
#   dosyalarını oluşturur. Kullanıcı içeriği yazdığında veya güncellediğinde,
#   `Hugo` bu içeriği derler ve sonuç olarak statik HTML dosyalarını üretir.
# `Wordpress`: `Wordpress`, veritabanı ve dinamik PHP kodu kullanarak içeriği
#   işler ve her istekte içeriği oluşturur. İçerik düzenleme ve görsel
#   düzenleme yetenekleri sunar.

# Performans ve Hız:
# `Hugo`: Statik siteler, önceden oluşturulmuş içeriği sunarak hızlı bir
#   performans sağlar. Çünkü her istekte içerik oluşturulması gerekmez.
# `Wordpress`: Dinamik siteler, içeriği her istekte oluşturduğu için
#   performans açısından daha yavaş olabilir.

# Kullanım Alanları:
# `Hugo`: Basit bloglar, kişisel web siteleri, belgelendirme siteleri gibi
#   statik içeriğe ihtiyaç duyan siteler için uygundur.
# `Wordpress`: Daha karmaşık web siteleri, haber siteleri, e-ticaret siteleri
#   gibi dinamik içeriğe ve geniş özelliklere ihtiyaç duyan projeler
#   için daha uygundur.

# Özelleştirme ve Esneklik:
# `Hugo`: Statik sitelerde özelleştirme ve değişiklik yapmak daha sınırlı
#   olabilir ancak performans ve güvenlik avantajları sunar.
# `Wordpress`: Dinamik sitelerde daha fazla özelleştirme ve esneklik
#   sağlayabilir, ancak karmaşıklık ve güvenlik sorunları olabilir.
###############################################################################