# ---- LINKS ----
# @link: https://docs.docker.com/network/
# @note: 
# ---------------

version: "3.7"

# my-test:
#   image: hello-world

###############################################################################
#                             NETWORKS                                        #
#/////////////////////////////////////////////////////////////////////////////#

networks:
  inception_network:
    name: inception_network
    driver: bridge

###############################################################################
#                             VOLUMES                                         #
#/////////////////////////////////////////////////////////////////////////////#

volumes: # For using backup all things.
  wp:
    name: wp
    # env_file: .env
    # env_printer:
      # image: "helloooasdf"
    # environment:
      # - asdf=asdf
    driver: local # We indicate that it works in locale, we can also write an ip address.
    driver_opts:
      type: none
      o: bind
      # device: /home/gorkem/data/wp #volume path
      device: /home/${USER}/data/wp #volume path
      # device: ${VOLUMES_WP} #volume path
  db:
    name: db
    driver: local # We indicate that it works in locale, we can also write an ip address.
    driver_opts:
      type: none
      o: bind
      # device: /home/gorkem/data/db #volume path
      device: /home/${USER}/data/db #volume path
      # device: ${VOLUMES_DB} #volume path
  prt:
    name: prt
    driver: local # We indicate that it works in locale, we can also write an ip address.
    driver_opts:
      type: none
      o: bind
      # device: /home/gorkem/data/prt #volume path
      device: /home/${USER}/data/prt #volume path
      # device: ${VOLUMES_PRT} #volume path

###############################################################################
#                             SERVICES                                        #
#/////////////////////////////////////////////////////////////////////////////#

services: # For containers(services).
  # ____MARIADB_____ #
  mariadb:
    container_name: mariadb # PDF asks us to create it with this name.
    build: ./requirements/mariadb/ # Dockerfile path locaiton.
    restart: always # If this container is closed, it restarts.
    env_file: .env
    volumes:
      - db:/var/lib/mysql # Mirroring this location to this location.
    networks:
      - inception_network # Using network.
  # ________________ #
  # _____NGINX______ #
  nginx: # For 'Web Server'.
    container_name: nginx # PDF asks us to create it with this name.
    build: ./requirements/nginx/ # Container's 'Dockerfile' path location for run this file.
    env_file: .env
    volumes:
      - wp:/var/www/wordpress
    networks:
      - inception_network
    depends_on:
      - wordpress
    ports:
      - "443:443" # Local port / Exported port.
  # ________________ #
  # ____WORDPRESS___ #
  wordpress:
    container_name: wordpress # PDF asks us to create it with this name.
    build: ./requirements/wordpress/
    env_file: .env
    volumes:
      - wp:/var/www/wordpress
    networks:
      - inception_network
    depends_on:
      - mariadb
  # ________________ #
  # ___REDIS_CACHE__ #
  redis:
    container_name: redis
    build: ./requirements/bonus/redis/
    restart: always
    env_file: .env
    networks:
      - inception_network
    depends_on:
      - nginx
    ports:
      - "6379:6379"
  # ________________ #
  # ___FTP-SERVER___ #
  ftp-server:
    container_name: ftp-server
    build: ./requirements/bonus/ftp-server/
    restart: always
    env_file: .env
    # environment:
      # - FTP_USER=${FTP_USERNAME}
      # - FTP_PASS=${FTP_PASSWORD}
    volumes:
      - wp:/home/${USER}
    networks:
      - inception_network
    depends_on:
      - nginx
    ports:
      - "21:21"
      - "21000-21010:21000-21010" #port aralığı
  # ________________ #
  # ____WEB-SITE____ #
  # website:
  #   container_name: website
  #   build: requirements/bonus/website/
  #   restart: always
  #   networks:
  #     - inception_network
  #   depends_on:
  #     - nginx
  #   ports:
  #     - "1111:1111"
  site:
    container_name: site
    build: requirements/bonus/site/
    restart: always
    networks:
      - inception_network
    depends_on:
      - nginx
    ports:
      - "1111:1111"
  # ________________ #
  # ____ADMINER_____ #
  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer/
    restart: always
    depends_on:
      - mariadb
    networks:
      - inception_network
    ports:
      - "8080:8080"
  # ________________ #
  # ____PORTAINER___ #
  portainer:
    container_name: portainer
    build: ./requirements/bonus/portainer/
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - prt:/data
    restart: always
    depends_on:
      - wordpress
    networks:
      - inception_network
    ports:
      - "9443:9443"