# ---- LINKS ----
# @link: https://docs.docker.com/network/
# @note: 
# ---------------

version: "3"

# my-test:
#   image: hello-world

###############################################################################
#                             NETWORKS                                        #
#/////////////////////////////////////////////////////////////////////////////#

networks:
  inception_network:
    # name: inception_network
    driver: bridge

###############################################################################
#                             VOLUMES                                         #
#/////////////////////////////////////////////////////////////////////////////#

volumes: # For using backup all things and reach all files inside container.
  wordpress_data:
    # env_file: .env
    # env_printer:
      # image: "helloooasdf"
    # environment:
      # - asdf=asdf
    driver: local # We indicate that it works in locale, we can also write an ip address.
    driver_opts:
      type: none
      o: bind
      # device: /home/gsever/data/wordpress #volume path
      device: /home/${USER}/data/wordpress #volume path
      # device: ${VOLUMES_WP} #volume path
  mariadb_data:
    driver: local # We indicate that it works in locale, we can also write an ip address.
    driver_opts:
      type: none
      o: bind
      # device: /home/gsever/data/mysql #volume path
      device: /home/${USER}/data/mysql #volume path
      # device: ${VOLUMES_DB} #volume path
  # prt:
  #   name: prt
  #   driver: local # We indicate that it works in locale, we can also write an ip address.
  #   driver_opts:
  #     type: none
  #     o: bind
  #     # device: /home/gsever/data/prt #volume path
  #     device: /home/${USER}/data/prt #volume path
  #     # device: ${VOLUMES_PRT} #volume path

###############################################################################
#                             SERVICES                                        #
#/////////////////////////////////////////////////////////////////////////////#

services: # For containers(services).
  # _____NGINX______ #
  nginx: # For 'Web Server'.
    container_name: nginx # PDF asks us to create it with this name.
    build: ./requirements/nginx/ # Container's 'Dockerfile' path location for run this file.
    env_file: .env
    volumes:
      - wordpress_data:/var/www/html
      # - wordpress_data:/etc/ssl/
    networks:
      - inception_network
    restart: always
    ports:
      - 443:443 # Local port / Exported port.
    # depends_on:
      # - adminer
      # - redis
      # - hugo
  # ________________ #